# Generated by Django 3.2.9 on 2022-07-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_requestmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodel',
            name='query',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
