# Generated by Django 3.2.9 on 2022-07-09 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_alter_requestmodel_query'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanmodel',
            name='password',
        ),
    ]
