# Generated by Django 3.2.9 on 2022-07-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_remove_loanmodel_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanmodel',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=100, null=True),
        ),
    ]
