# Generated by Django 3.2.9 on 2022-07-10 07:43

from django.db import migrations, models
import manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_loanmodel_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanmodel',
            name='loanid',
            field=models.CharField(blank=True, default=manager.models.generate_serial, max_length=100, null=True),
        ),
    ]
