# Generated by Django 3.2.9 on 2022-07-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_loanmodel_loanid'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestmodel',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
