# Generated by Django 3.2.9 on 2022-07-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_suggestionform'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestionform',
            name='subject',
            field=models.CharField(blank=True, help_text='subject', max_length=100, null=True, verbose_name='subject'),
        ),
    ]
