# Generated by Django 3.2.9 on 2022-07-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0020_auto_20220711_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanmodel',
            name='cibil_score',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanmodel',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanmodel',
            name='loan_purpose',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanmodel',
            name='monthly_emi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanmodel',
            name='monthly_income',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanmodel',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
