# Generated by Django 3.2.9 on 2022-07-13 11:00

from django.db import migrations, models
import manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0023_cardmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardmodel',
            name='config_id',
            field=models.CharField(blank=True, default=manager.models.generate_serial, max_length=100, null=True),
        ),
    ]
