# Generated by Django 3.2.9 on 2022-07-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0024_cardmodel_config_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardmodel',
            name='loan_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
