# Generated by Django 3.2.9 on 2022-07-13 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0026_loanmodel_emi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardmodel',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='cardmodel',
            name='name',
        ),
    ]
