# Generated by Django 3.2.9 on 2022-07-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0027_auto_20220713_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanmodel',
            name='card_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
