# Generated by Django 3.2.9 on 2022-07-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0029_loanmodel_eligible_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanmodel',
            name='page',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanmodel',
            name='page_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
