# Generated by Django 3.2.9 on 2022-07-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0030_auto_20220714_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanmodel',
            name='page_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
