# Generated by Django 3.2.9 on 2022-07-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0031_alter_loanmodel_page_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanmodel',
            name='paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
