# Generated by Django 3.2.9 on 2022-07-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0032_loanmodel_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanmodel',
            name='bank_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
