# Generated by Django 3.2.9 on 2022-07-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0035_cardmodel_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanmodel',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cardmodel',
            name='discount',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
