# Generated by Django 3.2.9 on 2022-07-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0036_auto_20220726_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanmodel',
            name='amount_due',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanmodel',
            name='amount_paid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
